### ISSUE TITLE
Tracking: Security, Trust models, Improving the status quo

### ISSUE THREAD

**Issue by kinnison** [rust-lang/rustup#2027]
In order to properly improve `rustup`'s security and trust model, we need to tackle a number of issues.  When these are all dealt with, then we'll be in a better position to protect our users and thus we can consider enabling some kind of mirror or alternative-dist-server-by-default mechanisms.

* [ ] Simple signature verification with embedded static key available on all `rustup` targets (#2028)
* [ ] Design and implement a better trust model than the above (#2029)
* [ ] Signed Windows binaries (#1568)

**Comment by elmarstellnberger** [comment]
gpg signatures can hardly improve security as long as the signing key is not kept offline. Additionally you would need to shield against physical access for that key; see: https://www.elstel.org/software/GnuPG-usage.html.en. The best way to improve security is to facilitate anonymous downloads via Tor. Intelligence agencies will never spoof all downloads (they would just spoof the upload instead). They target at specific individuals who can escape by using proper anonymization. Spoofing all downloads is something they do not do because f.i. the NSA does not want to export its technology to the Russians. Something that needs to be on your TODO list is:
* making downloads more robust - i.e. detect stalled downloads and reissue downloads from the position where they have stalled after a certain time period of inaction has elapsed; this is easy to do for http - I have also implemented this for debcheckroot (https://www.elstel.org/debcheckroot/). Besides this also users with unreliable internet connection from a non-security related context will profit from this
* offering plain sha512 or sha256sums with or without signing - such SHA512SUMS as they are the default for distributions like Debian can be downloaded easily via Tor. Verification is most straight forward, most secure and most easy to do.
The two proposed issues are easy to implement - and I would highly estimate their availability. That is something that will improve security in deed instead of some fancy 'fake' measures that can alone not solve the problem.

**Comment by elmarstellnberger** [comment]
You should be able to verify sha256sums without gpg, just by the sha256sum utility.

**Comment by elmarstellnberger** [comment]
'cargo fetch' is a good thing as long as you can use it with 'torsocks cargo fetch'. I have also already had offline rootkits so I recommend to never download by a direct internet connection. To make downloading most stable and most reliable I would also appreciate something like 'cargo fetch --print-urls' which lets you download with your favourite utility. If you can choose the downloading tool by yourself you can f.i. analyse why a download stalls and even more important you can download with any live CD where cargo may not be installed.

**Comment by kinnison** [comment]
So at this time, `cargo` is out of scope for the work we're doing on the trust model for `rustup`.  Again I ask that you hold off on pushing too hard until after we've opened discussion on the trust model work we're drafting.  It'll be a little while, but in the short term I've told you what we have available and if that's insufficient for you then we're unlikely to be able to do anything to satisfy you before we have our proper trust model rolled out.  Your point that people who need to use Tor in order to avoid scrutiny or interference from state actors is noted though, and will inform our design process, thank you.

**Comment by elmarstellnberger** [comment]
Support for cargo would be more important than for rustup as you can download the core distribution from https://forge.rust-lang.org/infra/other-installation-methods.html . To my mind a few improvements should suffice to make cargo work seamlessly with tor. May I file an own report for cargo?

**Comment by elmarstellnberger** [comment]
The issue for cargo can be found at: https://github.com/rust-lang/cargo/issues/7684

**Comment by nokri1000** [comment]
Nem érdekel


elmarstellnberger <notifications@github.com> ezt írta (időpont: 2019. dec.
8., V du. 3:21):

**Comment by elmarstellnberger** [comment]
Nem érdekel, mikor megerőszakolják a feleségedet, elégetik a házát és megölnek.

**Comment by ms-ati** [comment]
@kinnison Hi from Dec 2022! Two years later, wondering if any updates on the **trust model** for `rustup`?

**Comment by tabbyrobin** [comment]
Any updates on this?

**Comment by djc** [comment]
I think the main work that is going on is https://github.com/rust-lang/rfcs/pull/3724.

It doesn't seem actually productive to ask questions in all of these issues. If there were updates, they'd likely have been commented on already.

Did you have a specific question or concern that you'd like answered?

**Comment by tabbyrobin** [comment]
It seems the updates I was looking for are indeed, currently, in rust-lang/rfcs#3724 that you linked. This wasn't initially clear, even after having skimmed the discussion on the RFC. 

From a closer reading of the most [recent RFC 3724 text](https://github.com/rust-lang/rfcs/blob/ce5a794916a1143bce701af3594a39b58819c3a0/text/3724-theupdateframework.md), I realize that the work for cargo and rustup is tightly integrated, not just for the trust model, but *also for the actual implementation(s)*. 

I didn't realize this at first, because it's in a different repo. (From an outsider's perspective, rustup and cargo are very much distinct projects.) From the context of just this issue, one would get the impression that there was no movement since 2019. Digging through the history, it seems there were some other related RFCs etc in the intervening time, but which are now obsolete. 

I don't mean to spam your issue tracker. Given how quiet the relevant issues have been over the past few years, I didn't think my comments were excessive.

Questions:

- Are there any other key places for updates on this besides rust-lang/rfcs#3724?
- Is there a timeframe for implementation? Even a rough estimate could be helpful -- it could assist others in deciding whether they might want to dedicate time towards the topic, plan workarounds, etc. Even if the answer is "we do not have enough momentum to give any timeframe estimate", it is helpful to state that clearly.
- Is there any progress on implementation details for rustup/cargo? From my reading of RFC 3724, it outlines a trust model and recommends that cargo and rustup implement it jointly. But it leaves implementation out of scope.
- (If implementation is not currently underway...) Are there technical and/or social reasons that the rustup/cargo implementation (at least a rough sketch) cannot be started immediately?

**Comment by djc** [comment]
> I don't mean to spam your issue tracker. Given how quiet the relevant issues have been over the past few years, I didn't think my comments were excessive.

Replying to three different issues about substantially the same underlying topic at the same time (instead of waiting for an answer on one of the issues) does feel like "spam" from the receiving end, even if you didn't mean to.

I don't think there's any work ongoing within rustup, we're waiting for the outcome of the RFC. Any questions about the progress of the RFC (including implementation etc) are better directed to the RFC (authors).

> * (If implementation is not currently underway...) Are there technical and/or social reasons that the rustup/cargo implementation (at least a rough sketch) cannot be started immediately?

I think there are two interacting reasons:

1. The RFC is, in my read, not very close to being accepted in its current state, making any implementation effort at risk of having to be substantially changed/thrown away.
2. All rustup maintainers are participating on a volunteer basis, so there's limited appetite for taking large/complex projects especially if there's a bunch of risk as in (1).
