### ISSUE TITLE
1.27.0 release planning

### ISSUE THREAD

**Issue by djc** [rust-lang/rustup#3501]
@alex asked (privately) for a release after #3488 and #3490 so let's use this issue for tracking remaining work that we'd like to include in the next release and any other process surrounding the release process?

@rbtcollins can you share any context/thoughts around how releases have been managed in the past?

(I'm calling it 1.26.1 since I don't think there are any large changes in the public interface since the previous release, but I haven't checked that deeply so maybe 1.27.0 might be warranted?)

**Comment by rami3l** [comment]
@djc As a regular user I'd like to see `1.27.0`. You got us clap4 after all (#3444).

PS: I'm still using `rustup 1.26.0`, so you probably meant `1.26.1` in the title?

**Comment by djc** [comment]
Ahh yes -- I somehow seemed to remember that 1.26.2 was the latest release.

So why do you think it should be 1.27.0? Just because there are "new features"?

**Comment by rami3l** [comment]
> So why do you think it should be 1.27.0? Just because there are "new features"?

Do you remember the large amount of diffs that you had to change in order to pass the black box tests (for clap4)? I'm afraid someone is depending on that, though (s)he probably shouldn't.

**Comment by rami3l** [comment]
I think we can probably add a new milestone here? There are a few PRs that I want to address before cutting a new release 👀

**Comment by djc** [comment]
That works too. I like having a release planning issue because it's something interested users can subscribe to to keep up to date with the progress and comments can be added to discuss scope changes -- so in other projects I usually like to use task lists in a planning issue like this one.

**Comment by rami3l** [comment]
@djc Good. Let's keep it this way then.

I'll keep my list of issues "of interest" here:
* https://github.com/rust-lang/rustup/pull/3453
* https://github.com/rust-lang/rustup/pull/3108
  * https://github.com/rust-lang/rustup/pull/3506
* https://github.com/rust-lang/rustup/pull/3475
* https://github.com/rust-lang/rustup/pull/3464
* https://github.com/rust-lang/rustup/pull/3068
* https://github.com/rust-lang/rustup/pull/3225

The idea is that these are mostly PRs that have been reviewed but require checking again.

**Comment by rbtcollins** [comment]
The release process is documented in the rustup contributors guide. https://rust-lang.github.io/rustup/dev-guide/release-process.html

[tribal] We often ask for testers on reddit / rust-users
[tribal] we always increment the minor number unless [a] major compat break (which we haven't had : we've done minor compat breaks without bumping the major number), and [b] its a hotfix because the last release had a defect.

So the next # should 1.27.0

**Comment by alex** [comment]
Looks like we're down to a single issue remaining from the original list. Is there anything else for consideration for 1.27.0?

**Comment by heiher** [comment]
> Looks like we're down to a single issue remaining from the original list. Is there anything else for consideration for 1.27.0?

* https://github.com/rust-lang/rustup/pull/3536

**Comment by rami3l** [comment]
There are a few things to be done in order to actually release v1.27.0:

- [x] After a new `tracing_opentelemetry` update, merge ~~https://github.com/rust-lang/rustup/pull/3683~~ #3694.
- [x] Re-activate https://github.com/rust-lang/rustup/pull/3692, and manually downgrade OpenSSL back to where it was (the hints have been provided).
- [x] In #3699, update the changelog to match https://github.com/rust-lang/rustup/pull/3653.
- [x] In #3700, update the shasum (and date) in `rustup-init.sh` to point to the latest commit on the `master` branch.
- [x] Fast-forward `master` to `stable` and wait for the stable CI to turn green.
- [x] In https://github.com/rust-lang/blog.rust-lang.org/pull/1270, add a new release announcement post.
- [x] Inform t-release of a new stable release.
- [x] Tag the new release on the latest commit.
- [x] Address https://github.com/rust-lang/rustup/issues/3672.

**Comment by djc** [comment]
Note: we have a candidate release out for testing right now, see https://internals.rust-lang.org/t/seeking-beta-testers-for-rustup-1-27-0/20352/7.

Please send your feedback there or in this issue.

**Comment by alex** [comment]
Release is out! I think we can close this.
