### ISSUE TITLE
Meta: Don't update `Cargo.toml` when updating semver-compatible dependencies

### ISSUE THREAD

**Issue by rami3l** [rust-lang/rustup#3541]
> IMO we should not merge `Cargo.toml` changes that bump the semver requirement.

_Originally posted by @djc in https://github.com/rust-lang/rustup/issues/3540#issuecomment-1823960610_

cc https://github.com/killercup/cargo-edit/issues/552

**Comment by rami3l** [comment]
I did the research and found out that we can actually set [`rangeStrategy`](https://docs.renovatebot.com/configuration-options/#rangestrategy) to `update-lockfile` in `.github/renovate.json`, like in [this example](https://github.com/platformatic/platformatic/blob/d4d7fe2b7864e10ca2ce9a0f52e0437af707dd36/renovate.json#L6).

~~However, I'm not sure if this supports `cargo` or not. The docs page only says bundler, composer, npm, yarn, terraform and poetry are supported.~~

What I suggest if we want to get this fixed is:

- [x] ~~Verify the option's `cargo` compatibility. If needed, file an issue and wait for its implementation.~~ Wait until https://github.com/renovatebot/renovate/issues/22820 gets closed.
- [x] Update the `renovate.json` as specified above.
- [x] Revert `Cargo.toml` changes made in #3532 and #3540.

@djc Does that sound okay to you?

**Comment by djc** [comment]
Sounds good to me!

**Comment by rami3l** [comment]
Looks like the WIP that this issue will depend on (at https://github.com/renovatebot/renovate/pull/23968) has been closed.

I'm not that familiar with TypeScript but I guess I could possibly give it a try in December or so.
Or, if anyone else wants to work on it, please go ahead!

**Comment by rbtcollins** [comment]
Yah, its a missing feature in renovate :/. 

What I do here is just close pr's that are within the existing semver range except if they are security patches where we want to force the newer dep always.

**Comment by rami3l** [comment]
The patch I picked up (https://github.com/renovatebot/renovate/pull/25983) has been successfully merged!

**Comment by djc** [comment]
Great! Do we need to modify your configuration or can this issue be closed?

**Comment by rami3l** [comment]
@djc We need to modify the config (I've changed https://github.com/rust-lang/rustup/issues/3541#issuecomment-1824007018 to a to-do list). However I'll be very busy today, maybe later?

**Comment by rami3l** [comment]
Reopening due to the concern raised in https://github.com/rust-lang/rustup/pull/3569#issuecomment-1846206879.

**Comment by rami3l** [comment]
> ```js
>     // NOTE: Partial versions like '1.2' don't get converted to '^1.2'
>     // because isVersion('1.2') === false
>     // In cargo and in npm 1.2 is equivalent to 1.2.* so it is correct behavior.
> ```
> 
> It seems suspect? I don't know how `isVersion()` is used exactly. `1.2` in Cargo should be treated as `^1.2.0`.

_Originally posted by @djc in https://github.com/rust-lang/rustup/issues/3569#issuecomment-1846856400_

@djc I think `isVersion` means "is a valid semver string", for more examples you can refer to https://www.npmjs.com/package/semver.

For our specific case, on https://npm.runkit.com/semver you can see:

```js
> var semver = require("semver")
> !!semver.valid('1.2')
false
```

**Comment by rami3l** [comment]
https://github.com/renovatebot/renovate/pull/26263 has been created.

Update: The PR has been merged. Closing this issue hopefully for the one last time.
