### ISSUE TITLE
Windows: "called `Option::unwrap()` on a `None` value"

### ISSUE THREAD

**Issue by Baiyuetribe** [rust-lang/rustup#3936]
### Verification

- [X] I searched for recent similar issues at https://github.com/rust-lang/rustup/issues?q=is%3Aissue+is%3Aopen%2Cclosed and found no duplicates.
- [X] I am on the latest version of Rustup according to https://github.com/rust-lang/rustup/tags and am still able to reproduce my issue.

### Problem

windows on Arm64 still not work.
```log
thread 'main' panicked at src\cli\self_update.rs:652:45:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### Steps

reproduce
```sh
# my device: windows arm64
git clone https://github.com/rust-lang/rustup.git
cargo build --release
```
after,i got `rustup-init.exe`.
![image](https://github.com/rust-lang/rustup/assets/43716063/19f78eb0-3673-463d-b991-e32464dbdb4d)

### Rustup version

```console
latest
```

### Installed toolchains

```console
none
```

### OS version

```console
windows arm64
```

```[tasklist]
### Tasks
- [ ] https://github.com/rust-lang/rustup/pull/3938
```

**Comment by rami3l** [comment]
@Baiyuetribe Sorry for your bad experience!

Do you have the `HOME` environment variable set (https://superuser.com/a/1617017)? Rustup depends on that to work.

**Comment by rami3l** [comment]
Also, now that we're at it, maybe you can send a PR over **if that is indeed the root cause**? By adding a Windows-exclusive fallback to `USERPROFILE` for example.

The relevant code is here...
https://github.com/rust-lang/rustup/blob/79ba44c2814fa240cc64d1f4b1b1c324d75709ad/src/currentprocess.rs#L133

... and probably add a `.context()` call here:
https://github.com/rust-lang/rustup/blob/79ba44c2814fa240cc64d1f4b1b1c324d75709ad/src/currentprocess.rs#L51

... similar to what has been done below:
https://github.com/rust-lang/rustup/blob/79ba44c2814fa240cc64d1f4b1b1c324d75709ad/src/currentprocess.rs#L55

Many thanks in advance 🙇!

PS: Windows ARM64 is still a tier 2 target by far, meaning we still don't have the means to test it with our CI, we currently can only know that it builds correctly for Windows ARM64 (which it does).

**Comment by ChrisDenton** [comment]
> Do you have the `HOME` environment variable set (https://superuser.com/a/1617017)? Rustup depends on that to work.

Wait, why is rustup doing this directly? I thought it used the `home` crate? Did this change?

**Comment by ChrisDenton** [comment]
Needing the `HOME` environment variable seems like a regression.

**Comment by rami3l** [comment]
> > Do you have the `HOME` environment variable set (https://superuser.com/a/1617017)? Rustup depends on that to work.
> 
> Wait, why is rustup doing this directly? I thought it used the `home` crate? Did this change?

@ChrisDenton Blame: Introduced in https://github.com/rust-lang/rustup/commit/09972471be8e1fa29ba2c58cb22831742c49ad21, four years ago.

**Comment by ChrisDenton** [comment]
That's super weird because I have installed it within that time without having `HOME`. I mean, it doesn't exist by default.

**Comment by ChrisDenton** [comment]
It seems like we have two `home_dir` functions that do different things:

https://github.com/rust-lang/rustup/blob/79ba44c2814fa240cc64d1f4b1b1c324d75709ad/src/currentprocess.rs#L50-L53

https://github.com/rust-lang/rustup/blob/79ba44c2814fa240cc64d1f4b1b1c324d75709ad/src/currentprocess.rs#L130-L133

**Comment by rami3l** [comment]
> It seems like we have two `home_dir` functions that do different things:
> 
> https://github.com/rust-lang/rustup/blob/79ba44c2814fa240cc64d1f4b1b1c324d75709ad/src/currentprocess.rs#L50-L53
> 
> https://github.com/rust-lang/rustup/blob/79ba44c2814fa240cc64d1f4b1b1c324d75709ad/src/currentprocess.rs#L130-L133

@ChrisDenton My theory is that the former calls the latter with an indirection, in that `home_dir_with_env()` accepts a `home::env::Env` and calls its `home_dir()`:

```rs
/// Returns the path of the current user's home directory from [`Env::home_dir`].
pub fn home_dir_with_env(env: &dyn Env) -> Option<PathBuf> {
    env.home_dir()
}
```

**Comment by ChrisDenton** [comment]
Then I'm super confused why this isn't a problem for `x86_64`.

**Comment by rami3l** [comment]
> Then I'm super confused why this isn't a problem for `x86_64`.

@ChrisDenton I believe it should be, but we shouldn't trust the CI runner because from its POV setting `HOME` doesn't break anything.

**Comment by ChrisDenton** [comment]
Ah, I see. From testing it seems the published x86_64 installer works but not if I build from master. So it seems like this did regress at some point. I'm less confused now. This is a major regression because it means rustup-init is broken by default on Windows.

It also seems weird that we have two ways of getting rustup home that are implemented completely differently. In some places we use [`home::rustup_home`](https://github.com/rust-lang/rustup/blob/79ba44c2814fa240cc64d1f4b1b1c324d75709ad/src/cli/self_update.rs#L688) and in other places it's manually implemented using [`process.home_dir().unwrap().join(".rustup")`](https://github.com/rust-lang/rustup/blob/79ba44c2814fa240cc64d1f4b1b1c324d75709ad/src/cli/self_update.rs#L652)

**Comment by rami3l** [comment]
> Ah, I see. From testing it seems the published x86_64 installer works but not if I build from master. So it seems like this did regress at some point. I'm less confused now. This is a major regression because it means rustup-init is broken by default on Windows.

@ChrisDenton You mean somewhere between master and the v1.27.1 tag? Could you do a bisect in addition since I don't have a Windows machine near me, many thanks in advance 🙇 

> It also seems weird that we have two ways of getting rustup home that are implemented completely differently. In some places we use [`home::rustup_home`](https://github.com/rust-lang/rustup/blob/79ba44c2814fa240cc64d1f4b1b1c324d75709ad/src/cli/self_update.rs#L688) and in other places it's manually implemented using [`process.home_dir().unwrap().join(".rustup")`](https://github.com/rust-lang/rustup/blob/79ba44c2814fa240cc64d1f4b1b1c324d75709ad/src/cli/self_update.rs#L652)

That'll be a very good place to improve indeed.

**Comment by ChrisDenton** [comment]
> Could you do a bisect

Sure. It regressed in 204c8a9c.

> That'll be a very good place to improve indeed.

I think we should calculate rustup/cargo home once then cache it somewhere. Also those sanity checks look very unix-specific (unix paths and bash scripts). Not sure if they're relevant to Windows. Maybe there should be greater separation between platform specific bits. But that's a bigger job.

**Comment by rami3l** [comment]
@ChrisDenton Thanks a lot for helping out!

> Also those sanity checks look very unix-specific (unix paths and bash scripts). Not sure if they're relevant to Windows.

Rustup used to have runtime detection of OS instead of conditional compilation. The idea of this check is that it should be a no-op on Windows... I've set it as a part of #2424.

> It regressed in https://github.com/rust-lang/rustup/commit/204c8a9ca4e8a516865e381262a16b9eacb53901.

cc @djc (Looks like `OS_ENV` should be used for `OSProcess`. The two branches are written in the wrong order.)

**Comment by rami3l** [comment]
@Baiyuetribe Given @ChrisDenton's analysis, https://win.rustup.rs/aarch64 should work for you without problems.

**Comment by rami3l** [comment]
Please note that #3938 does NOT close this.

~~We'll still need to:~~
- ~~Refine the usages of [process.home_dir().unwrap().join(".rustup")](https://github.com/rust-lang/rustup/blob/79ba44c2814fa240cc64d1f4b1b1c324d75709ad/src/cli/self_update.rs#L652)~~;
- ~~Make the sanity check function platform-aware.~~

Looks like `do_pre_install_sanity_checks()` dates back from prehistoric times (v0.1.9, https://github.com/rust-lang/rustup/commit/008027172d1c7566467cc653556b3b8c232bc147), to defend against the old Rust distribution tools (namely "multirust.sh, rustc tarballs, and rustup.sh").

Now let's look at the files it verifies:
- `manifest-rustc` (without any prefix) is almost certainly gone: I cannot see this on my machine.
- `uninstall.sh` is... gone as well? Not quite sure, but a solution like this will definitely not work with Windows.
- `~/.rustup/rustup-version` is not for the Rust version of rustup, but rather its prototype `rustup.sh` (so there's no point in changing this to `rustup_home()`!), implemented in shell script, so is Unix only.

... so this function serves no purpose, at least not on Windows. My suggestion for now is to revert https://github.com/rust-lang/rustup/commit/008027172d1c7566467cc653556b3b8c232bc147 completely. @djc @ChrisDenton what do you think?

**Comment by Baiyuetribe** [comment]
> @Baiyuetribe Given @ChrisDenton's analysis, https://win.rustup.rs/aarch64 should work for you without problems.

thanks,it works 👍🏻

**Comment by ChrisDenton** [comment]
> My suggestion for now is to revert 0080271 completely

Makes sense to me! I think it served it's purpose in helping migration to rustup in ancient times but I don't think we still need to handle pre-1.0 stuff.
