### ISSUE TITLE
1.28.0 release planning

### ISSUE THREAD

**Issue by djc** [rust-lang/rustup#3998]
As discussed in https://github.com/rust-lang/rustup/pull/3985#issuecomment-2277529692, starting an issue for this because it makes it easier to have a discussion in one place on what items should be in the milestone(s).

I would propose that we remove these from the 1.28.0 milestone:

- #2590 
- #2789 
- #3651 

### Tasks
- [ ] https://github.com/rust-lang/rustup/pull/4079
- [ ] https://github.com/rust-lang/rustup/pull/4098
- [ ] https://github.com/rust-lang/rustup/pull/4105

**Comment by rami3l** [comment]
Remaining concerns for the beta release:
- [x] Related CI errors (https://github.com/rust-lang/rustup/actions/runs/12153440399)
- [x] https://github.com/rust-lang/rustup/pull/3921#discussion_r1664988935

The beta release is now available in https://internals.rust-lang.org/t/seeking-beta-testers-for-rustup-v1-28-0.

Remaining concerns for the stable release:
- [x] https://github.com/rust-lang/rustup/issues/4140
